# Generated by Django 3.0.5 on 2020-04-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ttle',
            new_name='title',
        ),
    ]
