# Generated by Django 3.0.5 on 2020-05-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Direcciones'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='being_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('GDL', 'Guadalajara')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sent_price',
            field=models.DecimalField(blank=True, decimal_places=5, default=False, max_digits=6),
        ),
    ]
