# Generated by Django 3.0.5 on 2020-05-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200425_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('P', 'Bikini primaveral'), ('I', 'Bikini invernal')], default='P', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'Nuevo'), ('O', 'En oferta')], default='N', max_length=2),
            preserve_default=False,
        ),
    ]
