# Generated by Django 3.0.5 on 2020-05-22 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20200521_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=30, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(max_length=100, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='address',
            name='suburb',
            field=models.CharField(max_length=100, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=6, verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sent_price',
            field=models.IntegerField(blank=True),
        ),
    ]
