# Generated by Django 3.0.5 on 2020-05-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200522_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='sent_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
