# Generated by Django 3.0.5 on 2020-05-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200524_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='point',
            field=models.CharField(default='', max_length=200, verbose_name='Punto medio'),
            preserve_default=False,
        ),
    ]
