# Generated by Django 3.0.5 on 2020-05-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200502_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_dat',
            new_name='ordered_date',
        ),
    ]
